version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/93a2210e23b5ac549632
          environment: ./My_Workspace.postman_globals.json